dist: trusty
sudo: false

language: node_js
node_js:
  - "lts/*"

addons:
  chrome: stable
  apt:
    packages:
      - sshpass

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test

after_success:
  - sh travis-merge-script.sh
  - npm run build -- --configuration production
  - sh travis-deploy-script.sh
  - cd backend & npm run start &
  - echo "Exit"
