dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - sshpass

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

after_success:
  - sh travis-merge-script.sh
  - npm run build -- --prod
  - sh travis-deploy-script.sh
